### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by fishi0x01** [waslchiraa/waslchiraa#22]
admin.himate.org
app.himate.org
merchant.himate.org

**Comment by simondeichsel** [comment]
@fishi0x01 on firefox on app.himate.org I get now an SSL error, is this expected?

**Comment by fishi0x01** [comment]
@simondeichsel I did not include intermediate certs in the certificate, that's why on some devices the trust chain is considered broken. I included the intermediate certificates now, so it should from now on work on all devices. Can you confirm?

**Comment by simondeichsel** [comment]
@fishi0x01 looks good in firefox in an anonymous window now. But I am not sure whether this happens because I already saved it as an exception.
@SarahPAV can you check, too?

**Comment by SarahPAV** [comment]
For me there is no SSL error :)

**Comment by fishi0x01** [comment]
On my browsers (FF, Chromium, Opera and my mobile phone opera) it works too. Considering it fixed.
