### ISSUE TITLE
refugee app Show voucher code on top in "my vouchers"

### ISSUE THREAD

**Issue by simondeichsel** [waslchiraa/waslchiraa#53]
currently the voucher-code for a reserved voucher is not shown in "my vouchers"
Show it. Prominently. On top.

**Comment by sananoussa** [comment]
<img width="316" alt="screen shot 2015-12-10 at 16 05 13" src="https://cloud.githubusercontent.com/assets/5710442/11718778/ef20c268-9f57-11e5-9b79-c02f15e03eb8.png">
do you mean like this ?

**Comment by simondeichsel** [comment]
Yes, great!
